version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .development_docker.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${POSTGRES_DB_NAME} --username ${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s

  server:
    build:
      context: .
      dockerfile: ./conf/dev/dockerFiles/main.Dockerfile
    env_file:
      - .development_docker.env
    volumes:
      - .:/var/www/api.schoolmeals.d
      - /var/www/api.schoolmeals.d/node_modules
    ports:
      - "5001:5001"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
     - db
    restart: always

volumes:
  db_data:
