version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres_school
    restart: always
  postgres_school:
    container_name: postgres_school
    image: postgres:14
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: